#ifndef BUREAUCRAT_HPP
#define BUREAUCRAT_HPP

#include <iostream>
#include <string>
#include "Form.hpp"

class Form;

class Bureaucrat
{
	private:
		const std::string name;
		int grade;
	public:
		Bureaucrat(const std::string name, int grade);
		Bureaucrat(const Bureaucrat& original);
		Bureaucrat& operator=(const Bureaucrat& rhs);
		~Bureaucrat();

		std::string getName() const;
		int			getGrade() const;

		void		incrementGrade();
		void		decrementGrade();

		void  signForm(Form& form);

		/* The subject says the exceptions must be catchable using try{} catch {}, and
			for this to work, the class must inherit from std::exception.
			The exceptions are nested inside Bureaucrat, because these
			exceptions belong to Bureaucrat and are used only for its errors.*/
		class GradeTooHighException : public std::exception
		{
			public:
				const char* what() const throw()
				{
					return "Grade too high";
				}
		};

		class GradeTooLowException : public std::exception
		{
			public:
				const char* what() const throw()
				{
					return "Grade too low";
				}
		};
};

std::ostream& operator<<(std::ostream& os, const Bureaucrat& object);

#endif

/*
	Throwing an exception means stopping normal execution and signaling
that an error occurred.
	Instead of returning an error value, the program throws an object,
and the program jumps to the nearest catch block.
	So throw = raise an error object.
	The expection class does not store any data.It only returns a message.
	Because of that:
	- No attributes → no constructor needed
	- No dynamic memory → no destructor needed
	The default ones generated by the compiler are enough.
	At the subject even says:
	"exception classes do not have to be designed in Orthodox Canonical Form"
	Meaning you don't need constructor, copy constructor, operator= and
destructor for exception classes.
*/
